### ISSUE TITLE
Node 18 support (module 108)

### ISSUE THREAD

**Issue by nschonni** [sass/node-sass#3251]
Support should land on April 19, 2022.

- [x] Add 18 to CI
- [x] Add the Module version to extensions.js
- [x] Update support table in README.md
- [x] Choose if this should be a v8 or v7.1 for the version
- [x] Update Windows builds to Windows 2019 https://github.com/sass/node-sass/issues/3212

Related but different timing:
- [ ] Node 12 EOL is on the 23rd https://github.com/sass/node-sass/issues/3250
- [ ] Node 17 EOL is June 1st 2020 https://github.com/sass/node-sass/issues/3252

**Comment by MartinHotmann** [comment]
> Support should land on April 19, 2022.

Are there any news on this? I tested it with Node18 and yes, with the lower versions (18.1 I guess) it worked, but with 18.7 and 18.6 it does not work. I would love to see this running on Node18 :)

Thanks!

**Comment by eduardocque** [comment]
any news about support to node 18 ?

**Comment by eduardocque** [comment]
@nschonni hi i would like to ask if you have an expected day to release this please

Regards

**Comment by MikeMcC399** [comment]
Node.js 18 moved to Active LTS status on Oct 25, 2022. See https://github.com/nodejs/release#release-schedule and https://nodejs.org/en/blog/release/v18.12.0/

**Comment by preichelt** [comment]
@nschonni any updates on Node 18 support now that 18 is Active LTS?

**Comment by pangyongsheng** [comment]
when will it be finshed

**Comment by pangyongsheng** [comment]
when will it be finshed

**Comment by preichelt** [comment]
I can at least confirm that we're successfully running node-sass `7.0.3` with Node `18.12.0` without any issues so far.

**Comment by MarcoKramer** [comment]
> I can at least confirm that we're successfully running node-sass `7.0.3` with Node `18.12.0` without any issues so far.

I can confirm the same. It did require installing `make` and `g++` to get it working.

**Comment by Nic128** [comment]
No it does not.
```
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (108)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v7.0.3
    at module.exports .....
    .....
```
We need this PR. https://github.com/sass/node-sass/pull/3257

**Comment by MikeMcC399** [comment]
@nschonni 

You wrote in this issue:
>  Node 17 EOL is June 1st 2020

That should be 2022, as you wrote in https://github.com/sass/node-sass/issues/3252.

In any case it is a date in the past! Maybe you'd like to correct this in the above original post?

**Comment by xzyfer** [comment]
Support for Node 18 and 19 has landed in v8.0.0. Huge thanks to @nschonni!

**Comment by denisecbiker** [comment]
I am upgrading form Node8 to 18 and running into a lot of issues with node-sass according to the verions i should  be installing node-sass@8 but when i try to do this it still tries to install node-sass@4.14.1 my logs fails then on postinstall of node-sass@4.14.1 and the error i get is

6771 verbose stack Error: command failed
6771 verbose stack     at ChildProcess.<anonymous> (C:\Users\w350000235\AppData\Roaming\nvm\v18.15.0\node_modules\npm\node_modules\@npmcli\run-script\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
6771 verbose stack     at ChildProcess.emit (node:events:513:28)
6771 verbose stack     at maybeClose (node:internal/child_process:1091:16)
6771 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
6772 verbose pkgid node-sass@4.14.1
6773 verbose cwd C:\Repos\AASolutions\clp_dms\dms-superadmin\src\Superadmin.WebApi\wwwroot
6774 verbose Windows_NT 10.0.19044
6775 verbose node v18.15.0
6776 verbose npm  v9.5.0
6777 error code 1
6778 error path C:\Repos\AASolutions\clp_dms\dms-superadmin\src\Superadmin.WebApi\wwwroot\node_modules\node-sass
6779 error command failed
6780 error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
6781 error Building: C:\Program Files\nodejs\node.exe C:\Repos\AASolutions\clp_dms\dms-superadmin\src\Superadmin.WebApi\wwwroot\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
6782 error gyp info it worked if it ends with ok
6782 error gyp verb cli [
6782 error gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
6782 error gyp verb cli   'C:\\Repos\\AASolutions\\clp_dms\\dms-superadmin\\src\\Superadmin.WebApi\\wwwroot\\node_modules\\node-gyp\\bin\\node-gyp.js',
6782 error gyp verb cli   'rebuild',
6782 error gyp verb cli   '--verbose',
6782 error gyp verb cli   '--libsass_ext=',
6782 error gyp verb cli   '--libsass_cflags=',
6782 error gyp verb cli   '--libsass_ldflags=',
6782 error gyp verb cli   '--libsass_library='
6782 error gyp verb cli ]
6782 error gyp info using node-gyp@3.8.0
6782 error gyp info using node@18.15.0 | win32 | x64
6782 error gyp verb command rebuild []
6782 error gyp verb command clean []
6782 error gyp verb clean removing "build" directory
6782 error gyp verb command configure []
6782 error gyp verb check python checking for Python executable "C:\Python311\python.exe" in the PATH
6782 error gyp verb `which` succeeded C:\Python311\python.exe C:\Python311\python.exe
6782 error gyp ERR! configure error 
6782 error gyp ERR! stack Error: Command failed: C:\Python311\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
6782 error gyp ERR! stack   File "<string>", line 1
6782 error gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
6782 error gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6782 error gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
6782 error gyp ERR! stack 
6782 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:419:12)
6782 error gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
6782 error gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
6782 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
6782 error gyp ERR! System Windows_NT 10.0.19044
6782 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Repos\\AASolutions\\clp_dms\\dms-superadmin\\src\\Superadmin.WebApi\\wwwroot\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
6782 error gyp ERR! cwd C:\Repos\AASolutions\clp_dms\dms-superadmin\src\Superadmin.WebApi\wwwroot\node_modules\node-sass
6782 error gyp ERR! node -v v18.15.0
6782 error gyp ERR! node-gyp -v v3.8.0
6782 error gyp ERR! not ok 
6782 error Build failed with error code: 1
6783 verbose exit 1

my package.json is   
{
  "name": "superadmin",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build sass -watch scss -o ./src/assets/css/style.scss",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "scss": "sass -watch scss -o ./src/assets/css/style.scss"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.1.2",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ngui/auto-complete": "^0.13.3",
    "angular-date-value-accessor": "^0.0.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "intl": "^1.2.5",
    "ng2-select-compat": "^1.3.1",
    "ng2-validation": "^4.2.0",
    "ngx-bootstrap": "^1.9.3",
    "ngx-datepicker": "0.0.0",
    "ngx-dnd": "1.0.3",
    "ngx-highlight": "0.0.3",
    "ngx-store": "^1.1.7",
    "ngx-toastr": "^5.2.1",
    "ngx-uploader": "^2.2.8",
    "rxjs": "^5.3.0",
     "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.5"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.4",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
 the command i run is npm install node-sass@latest

what can i do to get this installed and also do i need to have a specific verison of python and msbuildtools installed for this to work ?
