### ISSUE TITLE
0.10 Release checklist

### ISSUE THREAD

**Issue by nschonni** [sass/node-sass#388]
- [ ] Move nan to latest
- [ ] Get a stable tagged release for libsass
- [ ] Build platform binaries
- [ ] Depreciate `node-sass-middleware` so it can have a separate release lifecycle
- [ ] Expose new precision option from libsass #259
