### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by xzyfer** [sass/node-sass#904]
This is tracking the tasks required to release 3.0.0

- [x] bump nan to ^1.8.4 (@xzyfer https://github.com/sass/node-sass/pull/902)
- [x] ship remaining build/install PRs (@xzyfer)
  - [x] #907
  - [x] https://github.com/sass/node-sass/pull/880
  - [x] #912  
- [x] fix broken import graph resolution when watching (@xzyfer https://github.com/sass/node-sass/issues/905, #922)
- [x] create release notes for 3.0.0 (@xzyfer)
- [x] bump Libsass and sass-spec to ~~3.2.0~~ 3.2.2 (@xzyfer ~~#908~~ #920)
- [x] tag node-sass 3.0.0 (@xzyfer)
- [x] build OSX binaries (@xzyfer)
- [x] build linux binaries (@xzyfer)
- [x] build Windows binaries (@am11)
- [x] build FreeBSD binaries (@saper)
- [x] create a troubleshooting guide (@xzyfer #921)
  - [x] outline [linux debug steps](https://gist.github.com/am11/9f429c211822a9b15aee)
  - [x] outline [windows debug steps](https://gist.github.com/am11/e5de3c49c219f0811e1d)
  - [x] mention known issue with Windows and iojs (#870)
- [x] npm publish node-sass 3.0.0

### Optional

- [ ] build SmartOS binaries /cc @geekrohit @Candid

When this issue is closed 3.0.0 will be released.

Fixes #892.
Fixes #897.
Fixes #900.

**Comment by wintercounter** [comment]
Any estimated date? We have an important project for our sprint ending on Friday and having serious issues with Media Queries which this release would solve. Just curious, we can do workarounds...

**Comment by xzyfer** [comment]
We've just run into some issues with iojs 2.0.0 that we're looking into. Hopefully in the next 48hrs.

**Comment by xzyfer** [comment]
It is done.

**Comment by mrmartineau** [comment]
👏🏻 thanks to everyone for their hard work 👍🏻

**Comment by am11** [comment]
:tada:

**Comment by callumlocke** [comment]
thank you
